
- include: install-pip.yml

- name: make sure postgres dependencies are installed
  pip: name=psycopg2
  become_user: true

- name: create artifactory database in postgres
  postgresql_db: name={{artifactory_dbname}} encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' state=present login_host={{postgres_host}} port={{port}} login_user={{postgres_login_user}} login_password={{postgres_login_password}}

- name: make sure artifactory user has access to database
  postgresql_user: db={{artifactory_dbname}} name={{artifactory_username}} password={{artifactory_password}} priv=ALL role_attr_flags=NOSUPERUSER,NOCREATEDB login_host={{postgres_host}} port={{port}} login_user={{postgres_login_user}} login_password={{postgres_login_password}}
  ignore_errors: true

- name: make sure no other user can access the artifactory database
  postgresql_privs: db={{artifactory_dbname}} role=PUBLIC type=database priv=ALL state=absent login_host={{postgres_host}} port={{port}} login_user={{postgres_login_user}} login_password={{postgres_login_password}}


- name: download jdbc connector for postgres
  get_url:
    url: "{{ postgres_jdbc_jar }}"
    dest: "{{ artifactory_home }}/tomcat/lib"

- name: enable postgresql driver
  template:
    src: postgresql.properties
    dest: "{{ artifactory_home }}/etc/db.properties"
    mode: 0600

